### ISSUE TITLE
Document get_endpoint windows behavior

### ISSUE THREAD

**Issue by erickt** [erickt/rust-zmq#141]
@pfernie found in https://github.com/erickt/rust-zmq/pull/140 that get_endpoint has different behavior on windows than on unix systems. It doesn't appear to like `tcp:*:*` and upstream swaps it with `tcp://127.0.0.1:*`. We should document this.

**Comment by rotty** [comment]
It seems the actual difference in behavior is in the underlying
`connect()` implementation; I just ran strace on Linux like this:

    % strace -e connect -f target/debug/test-fc1629c3e3ecba1b 'test_exchanging_messages'
    ...
    [pid 10972] connect(11, {sa_family=AF_INET, sin_port=htons(35665), sin_addr=inet_addr("0.0.0.0")}, 16) = -1 EINPROGRESS (Operation now in progress)
    ...

So my preliminary analysis is that it's rather Linux which accepts the
wildcard address for connecting, at least (speculating here) when the
wildcard address is bound locally.

If this is not documented POSIX socket behavior, we should word this
in the documentation rather as leniency or "specialty" of Linux, than
as Windows shortcoming, and our tests might fail now (still) fail on
any POSIX platform with same symptoms as Windows did.

This [stackoverflow
entry](http://stackoverflow.com/questions/22384694/sockets-using-inaddr-any-on-client-side)
seems to indicate this is a Linux specific thing, but since
stackoverflow is not a standards text, I'll keep digging.

If on the other hand, POSIX prescribes this behavior, this is indeed a
restriction of the Windows platform, or at least the way libzmq
implements `zmq_connect()` there.
