### ISSUE TITLE
Missing zmq_msg_more wrapper

### ISSUE THREAD

**Issue by Eilie** [erickt/rust-zmq#75]

**Comment by dginev** [comment]
I would like to second this issue, I am interested in using the Rust wrapper for multi-part messages and it seems the support is currently not yet implemented.

Will see if I can take a first stab at a PR in this vein.

**Comment by hanckmann** [comment]
There is a multipart message send functionality, but I am unable to find the receive functions...

**Comment by rotty** [comment]
Did you already come up with something, @dginev? If so, (or you are about to) I will spare this area of the API of my attention. Otherwise, this might be something I might try my hand on after checking a few other boxes on my zmq TODO list.

**Comment by dginev** [comment]
In the end I managed to compromise and get by with just using ```.send(&data, SNDMORE)```. I'm still relatively novice when it comes to the technical peculiarities of multipart messages, and it has been a year since I took a careful look, so it's probably best for someone else to offer a solution here.

**Comment by rotty** [comment]
@dginev: There is `Socket::recv_multipart()` in current master, introduced by commit a04449aae2. So I'd say the issue is not that there is multipart receiving functionality missing, but that the underlying libzmq API  isn't completely exposed. We improve API coverage, and probably add an iterator-based API on top as well.

I'll try to come up with a pull request.

**Comment by dginev** [comment]
Oh, since the exact topic is receiving here, here is a simplification of the code I had ended up with back in 2015 when I was looking at this for reference. Usual caveat that I am a zmq novice.

```rust
let mut context = zmq::Context::new();
let mut sink = context.socket(zmq::PULL).unwrap();
let mut recv_msg = zmq::Message::new().unwrap();
// ...
while let Ok(_) = sink.recv(&mut recv_msg, 0) {
  // do something with recv_msg.deref(), e.g. write to a file stream
  match sink.get_rcvmore() {
    Ok(true) => {}, // keep receiving
    _ => break
  };
}
```

It seemed to work exactly as expected, managed to stream some huge messages in constant memory. But I am not at all certain if it's the best practice.

**Comment by birkenfeld** [comment]
I'm not sure where the difference is between `zmq_getsockopt(ZMQ_RCVMORE)` and `zmq_msg_get(ZMQ_MORE)` - it seems that the latter is newer and preferred.

**Comment by rotty** [comment]
@birkenfeld: yes, this was my impression as well.
