### ISSUE TITLE
Time for new release

### ISSUE THREAD

**Issue by plumenator** [erickt/rust-zmq#85]
It looks like several issues were fixed after the last release. Maybe  bump the version and publish to crates.io?

**Comment by birkenfeld** [comment]
Yes, please. The released version doesn't compile with current libc anymore. I'd rather not start and release my own fork.

**Comment by nlocnila** [comment]
+1

**Comment by kpcyrd** [comment]
It's currently not possible to use `zmq` as dependency with cargo. Can you please publish a new version?

**Comment by rotty** [comment]
As @erickt noted in PR #97, he'd be willing to share maintainership. Hopefully that works out, and we'll have a new release soonish.

**Comment by rotty** [comment]
As an update: I'll try to get a few more non-API-breaking changes into master:

- [ ] #35 
- [ ] #77 
- [ ] #93 
- [ ] #104 

After completing this checklist (assuming each item can be handled reasonably quickly), I'll nudge @erickt into publishing a release.

**Comment by erickt** [comment]
I'd suggest putting #104 off to after this release since it does have some semantic, albeit backwards compatible changes. I'm not sure what are the ultimate implications of having socket methods not require a mutable socket. The rest of the issues seem pretty reasonable.

**Comment by rotty** [comment]
I'm not entirely sure about #104 yet as well, but quite confident that `&self` should be OK for our socket wrapper. Anyway, I'll hold off merging it until 0.8 would otherwise be ready from my POV, and we can revisit it then, maybe being a bit wiser. Unfortunatly, I don't know any rust experts that I can bother with this question. Maybe I can bribe^Wconvince someone "authorative" to chime in on this question in the meantime.

**Comment by birkenfeld** [comment]
You could ask on http://internals.rust-lang.org

**Comment by rotty** [comment]
The release [happened recently](https://github.com/erickt/rust-zmq/releases/tag/v0.8.0), and was uploaded to [crates.io](https://crates.io/crates/zmq). Thanks to all contributors!
